{% set name = "lalsuite" %}
{% set version = "7.4" %}

# sub-package versions
{% set lal_version = "7.1.7" %}
{% set lalframe_version = "2.0.0" %}
{% set lalmetaio_version = "2.1.2" %}
{% set lalsimulation_version = "3.1.2" %}
{% set lalburst_version = "1.5.12" %}
{% set lalinspiral_version = "2.0.6" %}
{% set lalpulsar_version = "4.0.0" %}
{% set lalinference_version = "3.0.3" %}
{% set lalapps_version = "8.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://software.igwn.org/sources/source/lalsuite/{{ name }}-{{ version }}.tar.gz
  sha256: 2cb5d7792b842ef7cb4b126d1ed58c6276dcf5382cfd909175f6768bf072bbba

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install -vv .

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools >=38.3.0
  run:
    - python >=3.6
    - lal {{ lal_version }}.*
    - lalframe {{ lalframe_version }}.*
    - lalmetaio {{ lalmetaio_version }}.*
    - lalsimulation {{ lalsimulation_version }}.*
    - lalburst {{ lalburst_version }}.*
    - lalinspiral {{ lalinspiral_version }}.*
    - lalpulsar {{ lalpulsar_version }}.*
    - lalinference {{ lalinference_version }}.*
    - lalapps {{ lalapps_version }}.*

test:
  imports:
    - lal
    - lalframe
    - lalmetaio
    - lalsimulation
    - lalburst
    - lalinspiral
    - lalpulsar
    - lalinference
    - lalapps
  requires:
    - pip
  commands:
    - lalapps_version
    - python -m pip show {{ name }}
    - python -m pip check {{ name }}

about:
  home: https://wiki.ligo.org/Computing/LALSuite
  doc_url: https://lscsoft.docs.ligo.org/lalsuite/
  dev_url: https://git.ligo.org/lscsoft/lalsuite.git
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: COPYING
  summary: LSC Algorithm Library Suite
  description: |
    The LSC Algorithm Library Applications for gravitational wave data
    analysis.  This package contains applications that are built on tools
    in the LSC Algorithm Library.

extra:
  recipe-maintainers:
    - duncanmmacleod
    - skymoo
