{% set name = "lalsuite" %}
{% set version = "7.22" %}

# sub-package versions
{% set lal_version = "7.5.0" %}
{% set lalframe_version = "3.0.4" %}
{% set lalmetaio_version = "4.0.4" %}
{% set lalsimulation_version = "5.4.0" %}
{% set lalburst_version = "2.0.4" %}
{% set lalinspiral_version = "5.0.0" %}
{% set lalinference_version = "4.1.6" %}
{% set lalpulsar_version = "6.1.0" %}
{% set lalapps_version = "10.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://software.igwn.org/sources/source/lalsuite/{{ name }}-{{ version }}.tar.gz
  sha256: 4d8550475145e9859ec90f8287b48438f4a6730391bdfef92c4fb2dfe30e3db9

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install -vv .

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools >=38.3.0
  run:
    - python >=3.8
    - lal {{ lal_version }}.*
    - lalframe {{ lalframe_version }}.*
    - lalmetaio {{ lalmetaio_version }}.*
    - lalsimulation {{ lalsimulation_version }}.*
    - lalburst {{ lalburst_version }}.*
    - lalinspiral {{ lalinspiral_version }}.*
    - lalpulsar {{ lalpulsar_version }}.*
    - lalinference {{ lalinference_version }}.*
    - lalapps {{ lalapps_version }}.*

test:
  imports:
    - lal
    - lalframe
    - lalmetaio
    - lalsimulation
    - lalburst
    - lalinspiral
    - lalpulsar
    - lalinference
    - lalapps
  requires:
    - pip
    # needed for run_test.py
    - pytest
  source_files:
    # needed for run_test.py
    - setup.cfg
  commands:
    # run_test.py checks that the versions are up-to-date
    # show metadata
    - python -m pip show {{ name }}
    # check requirements
    - python -m pip check {{ name }}

about:
  home: https://wiki.ligo.org/Computing/LALSuite
  doc_url: https://lscsoft.docs.ligo.org/lalsuite/
  dev_url: https://git.ligo.org/lscsoft/lalsuite.git
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: COPYING
  summary: LSC Algorithm Library Suite
  description: |
    The LSC Algorithm Library Applications for gravitational wave data
    analysis.  This package contains applications that are built on tools
    in the LSC Algorithm Library.

extra:
  recipe-maintainers:
    - duncanmmacleod
    - skymoo
