{% set name = "lalsuite" %}
{% set version = "7.0" %}

# sub-package versions
{% set lal_version = "7.1.3" %}
{% set lalframe_version = "1.5.5" %}
{% set lalmetaio_version = "2.0.3" %}
{% set lalsimulation_version = "3.0.0" %}
{% set lalburst_version = "1.5.9" %}
{% set lalinspiral_version = "2.0.3" %}
{% set lalpulsar_version = "3.1.0" %}
{% set lalinference_version = "3.0.0" %}
{% set lalapps_version = "7.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

build:
  noarch: python
  number: 0

requirements:
  host:
    - jinja2
    - pip
    - python >=3.5
    - setuptools >=38.3.0
    - pyyaml
  run:
    - python >=3.5
    - lal {{ lal_version }}.*
    - lalframe {{ lalframe_version }}.*
    - lalmetaio {{ lalmetaio_version }}.*
    - lalsimulation {{ lalsimulation_version }}.*
    - lalburst {{ lalburst_version }}.*
    - lalinspiral {{ lalinspiral_version }}.*
    - lalpulsar {{ lalpulsar_version }}.*
    - lalinference {{ lalinference_version }}.*
    - lalapps {{ lalapps_version }}.*
    - python-lal {{ lal_version }}.*
    - python-lalframe {{ lalframe_version }}.*
    - python-lalmetaio {{ lalmetaio_version }}.*
    - python-lalsimulation {{ lalsimulation_version }}.*
    - python-lalburst {{ lalburst_version }}.*
    - python-lalinspiral {{ lalinspiral_version }}.*
    - python-lalpulsar {{ lalpulsar_version }}.*
    - python-lalinference {{ lalinference_version }}.*

test:
  imports:
    - lal
    - lalframe
    - lalmetaio
    - lalsimulation
    - lalburst
    - lalinspiral
    - lalpulsar
    - lalinference
    - lalapps
  requires:
    - pip
  commands:
    - lalapps_version
    - python -m pip show {{ name }}
    - python -m pip check {{ name }}

about:
  home: https://wiki.ligo.org/Computing/LALSuite
  doc_url: https://lscsoft.docs.ligo.org/lalsuite/
  dev_url: https://git.ligo.org/lscsoft/lalsuite.git
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: COPYING
  summary: LSC Algorithm Library Suite
  description: |
    The LSC Algorithm Library Applications for gravitational wave data
    analysis.  This package contains applications that are built on tools
    in the LSC Algorithm Library.

extra:
  recipe-maintainers:
    - duncanmmacleod
    - skymoo
