{% set name = "lalsuite" %}
{% set version = "6.66" %}

# sub-package versions
{% set lal_version = "6.21.0" %}
{% set lalframe_version = "1.5.0" %}
{% set lalmetaio_version = "1.6.0" %}
{% set lalsimulation_version = "1.10.0" %}
{% set lalburst_version = "1.5.4" %}
{% set lalinspiral_version = "1.10.0" %}
{% set lalpulsar_version = "1.18.2" %}
{% set lalinference_version = "1.11.5" %}
{% set lalapps_version = "6.25.1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

build:
  noarch: "python"
  number: 0

requirements:
  host:
    - jinja2
    - lockfile
    - pip
    - poetry 1.0.0
    - python >=3
    - pyyaml
  run:
    - python
    - lal {{ lal_version }}.*
    - lalframe {{ lalframe_version }}.*
    - lalmetaio {{ lalmetaio_version }}.*
    - lalsimulation {{ lalsimulation_version }}.*
    - lalburst {{ lalburst_version }}.*
    - lalinspiral {{ lalinspiral_version }}.*
    - lalpulsar {{ lalpulsar_version }}.*
    - lalinference {{ lalinference_version }}.*
    - lalapps {{ lalapps_version }}.*
    - python-lal {{ lal_version }}.*
    - python-lalframe {{ lalframe_version }}.*
    - python-lalmetaio {{ lalmetaio_version }}.*
    - python-lalsimulation {{ lalsimulation_version }}.*
    - python-lalburst {{ lalburst_version }}.*
    - python-lalinspiral {{ lalinspiral_version }}.*
    - python-lalpulsar {{ lalpulsar_version }}.*
    - python-lalinference {{ lalinference_version }}.*

test:
  imports:
    - lal
    - lalframe
    - lalmetaio
    - lalsimulation
    - lalburst
    - lalinspiral
    - lalpulsar
    - lalinference
    - lalapps
  requires:
    - pip
  commands:
    - lalapps_version
    - python -m pip show {{ name }}

about:
  home: "https://wiki.ligo.org/Computing/LALSuite"
  doc_url: "https://lscsoft.docs.ligo.org/lalsuite/"
  dev_url: "https://git.ligo.org/lscsoft/lalsuite/"
  license: "GPL-3.0-or-later"
  license_family: "GPL"
  license_file: "COPYING"
  summary: "LSC Algorithm Library Suite"
  description: |
    The LSC Algorithm Library Applications for gravitational wave data
    analysis.  This package contains applications that are built on tools
    in the LSC Algorithm Library.

extra:
  recipe-maintainers:
    - duncanmmacleod
    - skymoo
