appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: diZUbmQVUGzNmemRKeUhjyZfpHCcp9/F2CCizQ3s0AzjcgQl0hytOb51+LkdWHdGTrDA3Q7UknWr1/kWNol6Nhjd8elOvipLmGQobJqGLIrLGW18CG0Sn8cZt8e96h0pbUReB7CYJyzlHV2yu0qGWQ3zXbi4cNsFdNPvYIB5uNCuVZMBbL20olSFT3ZqZOY9Pr+hl17GWKUMHxXLgZuXNSLopF/dGJ5vjTR9MWuNhXufw8fDHea8zzF+2tmpxNcLIxzxU3wN7Fhu5vxC9/r5Hvx4H6KO3HfiAA+/PAOGL703GyJco6AQrEBQea1bj584Cn4gKaWZsdFWjqCrs5+FCY7C0Lm9HJBO6Ppnmrc6W1PH7+3tDadpSrKDEFJAxiJa5KP/tMF7F99MP+IVeAvf1c2V5VQEIMpG57m6kC2wDQ9/pw/CXL5EeMknOKVV0iPWAOeL2snk4LblQqoJibGz1uC9kZwOjsuojiakiGngqeUosMhvXADOvLMlgiXCrzMGt9A6Wycl/u+yF+NfxOSxzK5jmwr7jQ1ulMSTD1cWRbxpWL2RQ3ZAWL29UFQCGNwf5Yp0/fAhVJ+JNCegAoJBugOJU0nyZVFjqSwoBaY0TkQwMqPp5BFID1VDJcAWwzPt1t2kAQVmepTzt0oMz9+1ianbsbyOI9YaLnpQGKbrhIw=}
